config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :userpages, only: [:show, :edit, :update]
  resources :posts
  post '/posts/comment/:id', to: 'posts#create_comment' 
end

app/controllers/userpages_controller.rb
class UserpagesController < ApplicationController
  layout 'posts'
  before_action :set_userpage, only: [:show, :edit, :update]

  # GET /userpages/1
  def show; end

  # GET /userpages/1/edit
  def edit; end

  # PATCH/PUT /userpages/1
  def update
    if @user.update(userpage_params)
      redirect_to @user, notice: 'Userpage was successfully updated.'
    else
      render :edit
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userpage
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:userinfo).permit(:user_id, :username, :profile)
    end
end

app/helpers/userpages_helper.rb
module UserpagesHelper
end

app/views/userpages/_form.html.slim
= form_for @userpage do |f|
  - if @userpage.errors.any?
    #error_explanation
      h2 = "#{pluralize(@userpage.errors.count, "error")} prohibited this userpage from being saved:"
      ul
        - @userpage.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/userpages/edit.html.slim
h1 Editing userpage

== render 'form'

= link_to 'Show', @userpage
'  |
= link_to 'Back', root_path

app/views/userpages/show.html.slim
p#notice = notice

p ユーザー名
= current_user.userinfo.user_name
p 自己紹介 
= current_user.userinfo.profile

- @user.posts.each do |post|
  = image_tag post.image, show_post_path(post)

br
= link_to 'Back', root_path