config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :userpages, only: [:show, :edit, :update]
  resources :posts
  post '/posts/comment/:id', to: 'posts#create_comment' 
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :bookmarks
  has_many :comments
  has_many :tags, through: :post_tags

  mount_uploader :image, ImageUploader

  # タグの更新処理
  def save_tags tags
    current_tags = self.tags.pluck(:name) unless self.tags.nil?

    old_tags = current_tags.collect!{|e| e unless tags.include? }.compact!
    new_tags = tags.collect!{|e| e unless current_tags.include? }.compact!

    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end
    
    new_tags.each do |new_name|
      image_tags = Tag.find_or_create_by(name: new_name)
      self.tags << image_tags
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show, :update, :destroy, :create_comment]
  before_action :authenticate_user!

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
    @comments = @post.comments.order("created_at ASC")
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def edit
    if current_user.id == @post.user_id
      @edit_tag_list = @post.tags.pluck(:name).join(',')
    else
      redirect_to root_path, notice: 'This operation is not allowed.'
    end
  end
  
  # POST /posts
  def create
    @post = current_user.posts.build post_params
    tag_list = params[:tag_list].split(',')

    if @post.save
      @post.save_tags tag_list
      redirect_to root_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # POST /comment
  def create_comment
    @comment = @post.comments.build(comment_params)

    if @post.save
      redirect_to @post, notice: 'Comment was successfully created'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    tag_list = params[:tag_list].split(',')

    if @post.update post_params
      @post.save_tags tag_list
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redurect_to posts_url, notice: 'Post was successfully destoryed'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:user_id, :post_id, :comment)
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      begin
        params.require(:post).permit(:user_id, :image, :bookmark_count, :comment_count)
      rescue 
        flash[:message] = "アップロードする画像を選択して下さい"
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
= form_for(post) do |f|
  - if post.errors.any?
    #error_explanation
      h2
        = pluralize(post.errors.count, "error")
        |  prohibited this post from being saved:
      ul
        - post.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :title
    = f.text_field :title

    .article-tags-field
      = f.label "category"
      ul#article-tags
    
    = f.label :image
    = f.file_field :image

  .actions
    = f.submit "画像をアップロードする"

app/views/posts/edit.html.slim
h1
  | Edit Post
= render 'form', post: @post
= link_to 'Back', posts_path

app/views/posts/index.html.slim
p#notice
  = notice
h1
  | 投稿一覧
tbody
  - @posts.each do |post|
    tr
      td
        = link_to image_tag(post.image_url(:thumb)), post
br

app/views/posts/new.html.slim
h1
  | New Post
= h(flash[:message])
= render 'form', post: @post
= link_to 'Back', root_path

app/views/posts/show.html.slim
p#notice
  = notice
div
  = image_tag(@post.image_url(:thumb))

- @comments.each do |c|
  = c.comment

= form_for @post.comments.new, url: { controller: :posts, action: :create_comment } do |f|
  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field :post_id, value: @post.id
  = f.label :comment
  = f.text_area :comment
  = f.submit "コメントする"

= link_to 'Back', root_path