config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :userpages, only: [:show, :edit, :update]
  resources :posts
  post '/posts/comment/:id', to: 'posts#create_comment' 
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Pictorium
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      = yield

app/views/layouts/posts.html.slim
doctype html
html
  head
    title
      | Pictorium
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
    / = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'Pictorium', root_path, class: 'navbar-brand'
        #navbar.navbar-collapse.collapse
          ul.nav.navbar-nav
            li = link_to '新規投稿', new_post_path
          ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              = link_to "ログアウト", destroy_user_session_path
              = link_to "設定", userpage_path(current_user)
            - else
              = link_to 'ログイン', new_user_session_path
    .container
      = yield